language: ruby

branches:
  only:
    - master

env:
  - RAGEL=ON

before_install:
  - gem update --system
  - gem install bundler
  - gem update
  - gem --version
  - travis_retry sudo apt-get update -qq
  - travis_retry bash -c "if [[ \"${RAGEL}\" == ON ]]; then sudo apt-get install -qq ragel; fi"

rvm:
  - '1.8.7'
  - '1.9.3'
  - '2.0.0'
  - '2.1.10'
  - '2.2.6'
  - '2.3.4'
  - '2.4.1'

matrix:
  allow_failures:
    - rvm: '1.8.7'

script: 'bundle exec rake test:full'

